### ISSUE TITLE
Is `config_file` really required?

### ISSUE THREAD

**Issue by WoWaster** [chipsalliance/verible-linter-action#36]
Hi! My colleagues and I are trying to set up this action in our repository. We've copied your example from README. VS Code checked the input using your schema from [action.yml](https://github.com/chipsalliance/verible-linter-action/blob/main/action.yml) and gave us the following warning:
```
Missing required input config_file
```

Your example is working fine without the `config_file` argument. Maybe it shouldn't be required in [action.yml](https://github.com/chipsalliance/verible-linter-action/blob/main/action.yml)?

**Comment by tgorochowik** [comment]
That's right, the config file is not realy required, without it the defaults will be used for invoking Verible.

#37 should fix this
